services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5434:5432"
    container_name: CommiSysPrismaDB
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: test
